---
title: "Analysis"
output: pdf_document
---

```{r}
data <- read.csv("harmonized_Oct10_v2.csv") 
```

```{r}
library(tidyverse)
library(SiZer)
library(HERON)
```

```{r}
#for log response ratio, we need the mean and sd/n of each treatment 
summary(data)

mean_sd <- data %>%
  filter(!is.na(Response.Variable)) %>%
  filter(!is.na(Treatment)) %>%
  group_by(source, Date, Treatment) %>%
  summarise(means = mean(Response.Variable),
            response_sd = sd(Response.Variable),
            sample_size = n(),
            CV = sd(Response.Variable)/mean(Response.Variable))

head(mean_sd)

write.csv(mean_sd, "LR_master_file.csv")
```

```{r}
#For sizer analysis to find changes in linear trend sign in a time series
data_sub <- data %>%
  filter(!is.na(Response.Variable)) %>%
  filter(source == "SBC_algal_biomass_2008-2024_processed_corrected.csv") %>%
  filter(Treatment == "ANNUAL")

data_sub$Date <- as.numeric(data_sub$Date)
data_sub$Response.Variable <- as.numeric(data_sub$Response.Variable)

sizer_obj <- SiZer::SiZer(x = data_sub[["Date"]], y = data_sub[["Response.Variable"]],
                          h = c(2, 10), degree = 1, derv = 1, grid.length = 100)

# Plot (and export) the SiZer object with horizontal lines of interest
png(filename = "SBCA_SiZer-plot.png",
    width = 5, height = 5, res = 720, units = 'in')
HERON::sizer_plot(sizer_object = sizer_obj, bandwidth_vec = 5)#bandwidth specifies the window (the range of the y axis on the blobby graph) Greater bandwidth means a wider window and is less sensitive to changes in the slope and vice versa. 

dev.off()

#from this point on, analytical choices have been made regarding the bandwidth.
# Identify inflection points/slope changes
sizer_info <- HERON::sizer_slice(sizer_object = sizer_obj, bandwidth = 5)#must match the bandwidth specified in line 50. 

#could specify different bandwidth for each site because of different sampling duration or use the same bandwidth for all sites. If some sites had non-uniform sampling over time, sizer might interpret periods with less sampling to be breaks. 

# If there are changes (changes in slope e.g., pos to none, neg to none) and/or inflections (changes from pos to neg or vice versa), find inflections
inflects_raw <- c(sizer_info$neg_to_pos, sizer_info$pos_to_neg)
inflects <- inflects_raw[!is.na(inflects_raw)]
```

```{r}
place_info <- HERON::id_slope_changes(raw_data = data_sub, sizer_data = sizer_info,
                                        x = "Date", y = "Response.Variable",
                                        group_dig = 5)
  
# Plot 
demo_plot <- HERON::sizer_ggplot(raw_data = place_info, sizer_data = sizer_info,
                                   x = "Date", y = "Response.Variable",
                                   trendline = 'sharp', vline = "changes",
                                   sharp_colors = c("#bbbbbb", "green")) + #gray means neutral and green means non-neutral (could be pos or neg)
ggtitle(label = paste0("h = 5 Slope Changes"))

ggplot2::ggsave(filename = "sizer_SBCA_ggplot.png",
                height = 8, width = 8)
```

